version: '2'

services:
  radiodb:
    image: mysql:5.6
    container_name: radiodb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --performance-schema=false --table-definition-cache=400
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - radio

networks:
  radio:
    external: true
