version: '2'

services:
  radiodb:
    image: mysql:5.6
    container_name: radiodb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --performance-schema=false --table-definition-cache=400
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - radio
    restart: always

  radioapp:
    image: net-radio-archive
    build:
      context: .
    container_name: radioapp
    volumes:
      - working:/working
      - archive:/archive
      - ./data/log:/myapp/log
    networks:
      - radio
    depends_on:
      - radiodb
    links:
      - radiodb:mysql
    restart: always

networks:
  radio:
    external: true

volumes:
  working:
    driver: local
    driver_opts:
      type: cifs
      device: //${HOST}/${ROOT_PATH}/radio_kurari/working
      o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},rw,file_mode=0777,dir_mode=0777"
  archive:
    driver: local
    driver_opts:
      type: cifs
      device: //${HOST}/${ROOT_PATH}/radio_kurari/archive
      o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},rw,file_mode=0777,dir_mode=0777"
